// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity (user id, email) of the caller, verified from the OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const identity = { user_id: ctx.getUserId(), email: ctx.getUserEmail(), client_id: ctx.getClientId() };
    return {
      content: [{ type: "text", text: JSON.stringify(identity) }],
      structuredContent: identity
    };
  }
});

// src/lib/mcp/tools/list_meses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
var EXTERNAL_SUPABASE_URL = "https://srbyogadhamglfatjlbx.supabase.co";
var EXTERNAL_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYnlvZ2FkaGFtZ2xmYXRqbGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0OTQwNzEsImV4cCI6MjA5MzA3MDA3MX0.YPBOAFa4uABQFejONlu0B2P57WRA8ggvtcY6HtmxsmM";
function supabaseForUser(ctx) {
  return createClient(EXTERNAL_SUPABASE_URL, EXTERNAL_SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list_meses.ts
var list_meses_default = defineTool2({
  name: "list_meses",
  title: "List available months",
  description: "List the distinct a\xF1o_mes_num (e.g. 202606 = June 2026) that have financial data available for the signed-in user's companies.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("v_meses_disponibles").select("a\xF1o_mes_num").order("a\xF1o_mes_num", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const meses = Array.from(new Set((data ?? []).map((r) => r.a\u00F1o_mes_num)));
    return {
      content: [{ type: "text", text: JSON.stringify(meses) }],
      structuredContent: { meses }
    };
  }
});

// src/lib/mcp/tools/get_esf.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var get_esf_default = defineTool3({
  name: "get_esf",
  title: "Get Estado de Situaci\xF3n Financiera",
  description: "Return the ESF (balance sheet) rows for a company and month. Use list_meses first to discover available a\xF1o_mes_num. compania is one of 'IQLICK', 'PROHUB S.A.S.', or 'Todas' (consolidated).",
  inputSchema: {
    compania: z.string().min(1).describe("Company name, e.g. 'PROHUB S.A.S.' or 'Todas' for consolidated."),
    ano_mes_num: z.number().int().describe("Period as YYYYMM integer, e.g. 202606 for June 2026.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ compania, ano_mes_num }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("v_esf_resumida").select("orden,nivel,seccion,grupo_titulo,concepto,cuenta_key,signo,valor_presentacion,saldo_acum").eq("a\xF1o_mes_num", ano_mes_num).eq("compania", compania).neq("nivel", "CuentaERI").order("orden", { ascending: true }).limit(2e3);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_eri.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_eri_default = defineTool4({
  name: "get_eri",
  title: "Get Estado de Resultados Integral",
  description: "Return the ERI (income statement) rows for a company and month. compania is one of 'IQLICK', 'PROHUB S.A.S.', or 'Todas' (consolidated).",
  inputSchema: {
    compania: z2.string().min(1),
    ano_mes_num: z2.number().int().describe("Period as YYYYMM integer, e.g. 202606.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ compania, ano_mes_num }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("v_eri_por_mes").select("orden,nivel,seccion,grupo_titulo,concepto,cuenta_key,signo,valor_presentacion,saldo_mes").eq("a\xF1o_mes_num", ano_mes_num).eq("compania", compania).order("orden", { ascending: true }).limit(2e3);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var EXTERNAL_SUPABASE_PROJECT_REF = "srbyogadhamglfatjlbx";
var mcp_default = defineMcp({
  name: "iqlick-mcp",
  title: "iQlick Control Financiero",
  version: "0.1.0",
  instructions: "Tools to read Prohub/iQlick financial data (Estado de Situaci\xF3n Financiera, Estado de Resultados Integral). Call list_meses first to find available a\xF1o_mes_num, then get_esf or get_eri with a compania ('IQLICK', 'PROHUB S.A.S.', or 'Todas') and the a\xF1o_mes_num as YYYYMM.",
  auth: auth.oauth.issuer({
    issuer: `https://${EXTERNAL_SUPABASE_PROJECT_REF}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_meses_default, get_esf_default, get_eri_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
